name: Deploy Website

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        type: choice
        options:
          - Development
          - Test

jobs:  
  build-and-deploy:
    name: "Build & Deploy"
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ACR_NAME: ${{ vars.ACR_NAME }}
      ACR_LOGIN_SERVER: ${{ vars.ACR_NAME }}.azurecr.io
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
      RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }}
      WEBSITE_NAME: ${{ vars.ENV_PREFIX }}-app-web
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId": "${{ env.ARM_CLIENT_ID }}",
              "clientSecret": "${{ env.ARM_CLIENT_SECRET }}",
              "tenantId": "${{ env.ARM_TENANT_ID }}",
              "subscriptionId": "${{ env.ARM_SUBSCRIPTION_ID }}"
            }

      - name: ACR Login
        run: az acr login --name $ACR_NAME

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Website Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./web/feat.web/Dockerfile
          push: true
          tags: ${{ env.ACR_LOGIN_SERVER }}/feat-web:${{ github.sha }}

      - name: Update Website App Service
        run: |
          az webapp config container set \
            --name "$WEBSITE_NAME" \
            --resource-group "$RESOURCE_GROUP" \
            --docker-custom-image-name "$ACR_LOGIN_SERVER/feat-web:${{ github.sha }}"
