name: Deploy - Documentation
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'resources/tech_docs_template/**'
      - '.github/workflows/generate-tf-docs.yaml'
      - '.github/workflows/deploy-documentation.yaml'

jobs:
  build:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v5

      - name: Deploy GitHub Pages Site
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: resources/mkdocs.yml
